name: Build Diffing Engine(s)

on:
  pull_request:
    branches: [ 'main' ]
    paths-ignore: [ 'docs/**' ]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Build differs
      run: hatch run build
    - name: Commit differ
      run: |
        git config --global user.name 'JSv4'
        git config --global user.email 'JSv4@users.noreply.github.com'
        git commit -am "Engine Builds"
        git push
